// lib/scan-types.ts
import type { AllChecks, ScanBadge } from './checks';
import type { ApiScoreResult } from './api-score';

export interface AgentSuggestion {
  name: string;
  description: string;
  relevance: string;
}

export interface McpGithubHint {
  url: string;
  full_name: string;
  stars: number;
  owner: string;
}

/**
 * AI-generation disclosure per EU AI Act Art. 50 (applies 2 Aug 2026).
 * Identifies which fields in the response are generated by an LLM and
 * which model produced them. Public APIs MUST set this so consumers can
 * apply their own disclosure to end-users.
 */
export interface AIGenerationDisclosure {
  /** True if any field on this response was produced by an LLM. */
  ai_generated: boolean;
  /** Provider + model identifier — e.g. "anthropic/claude-sonnet-4-5". */
  model?: string;
  /** Field paths that were AI-generated. Subset of the response keys. */
  fields?: string[];
}

export interface ScanResult {
  company: string;
  industry: string;
  summary: string;
  agent_suggestions: AgentSuggestion[];
  badge: ScanBadge;
  score: number;
  checks_total?: number;
  checks: AllChecks;
  recommendations: string[];
  severity_counts: { critical: number; important: number; info: number };
  scan_id: string | null;
  isDemo: boolean;
  api_score?: ApiScoreResult | null;
  scanned_at: string; // ISO 8601
  mcp_github_hint?: McpGithubHint | null;
  /**
   * AI-generation disclosure per EU AI Act Art. 50. Always present on
   * scans where Claude or any other LLM produced text content. Required
   * to be machine-readable per the regulation; we set it on every
   * response so downstream API consumers can rely on it being there.
   */
  ai_disclosure?: AIGenerationDisclosure;
}

export const DEFAULT_AGENT_SUGGESTIONS: AgentSuggestion[] = [
  {
    name: "Kundtjänst-agent",
    description: "Svarar på ärenden genom att koppla ihop CRM, mail och docs.",
    relevance: "Vanlig agent-typ som fungerar för de flesta verksamheter.",
  },
  {
    name: "Compliance-agent",
    description: "Övervakar GDPR och EU AI Act-krav automatiskt.",
    relevance: "Relevant för alla svenska företag inför EU AI Act aug 2026.",
  },
  {
    name: "Data-agent",
    description: "Samlar och sammanställer data från era system.",
    relevance: "Grundläggande automatisering för alla verksamheter.",
  },
];
